"""initial schema

Revision ID: 94d20ece01de
Revises:
Create Date: 2026-03-22 09:14:24.878068

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "94d20ece01de"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
